version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: metaltec-db
    restart: always
    environment:
      POSTGRES_USER: metaltec
      POSTGRES_PASSWORD: metaltec123
      POSTGRES_DB: metaltec_estoque
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
